# dockerfile for development with on unstable go-swagger
FROM golang:1.15-buster

ENV GO111MODULE on

# Use unstable go-swagger build
# RUN go get github.com/youyuanwu/go-swagger@a6f47452c70598306bd7778e23c0df7114fb7b98
# RUN go-swagger version