// Code generated by go-swagger; DO NOT EDIT.

package config

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/go-openapi/dockerctl/models"
)

// ConfigListReader is a Reader for the ConfigList structure.
type ConfigListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ConfigListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewConfigListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewConfigListInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 503:
		result := NewConfigListServiceUnavailable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewConfigListOK creates a ConfigListOK with default headers values
func NewConfigListOK() *ConfigListOK {
	return &ConfigListOK{}
}

/* ConfigListOK describes a response with status code 200, with default header values.

no error
*/
type ConfigListOK struct {
	Payload []*models.Config
}

func (o *ConfigListOK) Error() string {
	return fmt.Sprintf("[GET /configs][%d] configListOK  %+v", 200, o.Payload)
}
func (o *ConfigListOK) GetPayload() []*models.Config {
	return o.Payload
}

func (o *ConfigListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewConfigListInternalServerError creates a ConfigListInternalServerError with default headers values
func NewConfigListInternalServerError() *ConfigListInternalServerError {
	return &ConfigListInternalServerError{}
}

/* ConfigListInternalServerError describes a response with status code 500, with default header values.

server error
*/
type ConfigListInternalServerError struct {
	Payload *models.ErrorResponse
}

func (o *ConfigListInternalServerError) Error() string {
	return fmt.Sprintf("[GET /configs][%d] configListInternalServerError  %+v", 500, o.Payload)
}
func (o *ConfigListInternalServerError) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *ConfigListInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewConfigListServiceUnavailable creates a ConfigListServiceUnavailable with default headers values
func NewConfigListServiceUnavailable() *ConfigListServiceUnavailable {
	return &ConfigListServiceUnavailable{}
}

/* ConfigListServiceUnavailable describes a response with status code 503, with default header values.

node is not part of a swarm
*/
type ConfigListServiceUnavailable struct {
	Payload *models.ErrorResponse
}

func (o *ConfigListServiceUnavailable) Error() string {
	return fmt.Sprintf("[GET /configs][%d] configListServiceUnavailable  %+v", 503, o.Payload)
}
func (o *ConfigListServiceUnavailable) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *ConfigListServiceUnavailable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
