// Code generated by go-swagger; DO NOT EDIT.

package cli

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"

	"github.com/go-swagger/dockerctl/client/container"
	"github.com/go-swagger/dockerctl/models"

	"github.com/go-openapi/swag"
	"github.com/spf13/cobra"
)

// makeOperationContainerContainerUpdateCmd returns a cmd to handle operation containerUpdate
func makeOperationContainerContainerUpdateCmd() (*cobra.Command, error) {
	cmd := &cobra.Command{
		Use:   "ContainerUpdate",
		Short: `Change various configuration options of a container without having to recreate it.`,
		RunE:  runOperationContainerContainerUpdate,
	}

	if err := registerOperationContainerContainerUpdateParamFlags(cmd); err != nil {
		return nil, err
	}

	return cmd, nil
}

// runOperationContainerContainerUpdate uses cmd flags to call endpoint api
func runOperationContainerContainerUpdate(cmd *cobra.Command, args []string) error {
	appCli, err := makeClient(cmd, args)
	if err != nil {
		return err
	}
	// retrieve flag values from cmd and fill params
	params := container.NewContainerUpdateParams()
	if err, _ := retrieveOperationContainerContainerUpdateIDFlag(params, "", cmd); err != nil {
		return err
	}
	if err, _ := retrieveOperationContainerContainerUpdateUpdateFlag(params, "", cmd); err != nil {
		return err
	}
	if dryRun {

		logDebugf("dry-run flag specified. Skip sending request.")
		return nil
	}
	// make request and then print result
	msgStr, err := parseOperationContainerContainerUpdateResult(appCli.Container.ContainerUpdate(params))
	if err != nil {
		return err
	}
	if !debug {

		fmt.Println(msgStr)
	}
	return nil
}

// registerOperationContainerContainerUpdateParamFlags registers all flags needed to fill params
func registerOperationContainerContainerUpdateParamFlags(cmd *cobra.Command) error {
	if err := registerOperationContainerContainerUpdateIDParamFlags("", cmd); err != nil {
		return err
	}
	if err := registerOperationContainerContainerUpdateUpdateParamFlags("", cmd); err != nil {
		return err
	}
	return nil
}

func registerOperationContainerContainerUpdateIDParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	IDDescription := `Required. ID or name of the container`

	var IDFlagName string
	if cmdPrefix == "" {
		IDFlagName = "id"
	} else {
		IDFlagName = fmt.Sprintf("%v.id", cmdPrefix)
	}

	var IDFlagDefault string

	_ = cmd.PersistentFlags().String(IDFlagName, IDFlagDefault, IDDescription)

	return nil
}
func registerOperationContainerContainerUpdateUpdateParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	var UpdateFlagName string
	if cmdPrefix == "" {
		UpdateFlagName = "update"
	} else {
		UpdateFlagName = fmt.Sprintf("%v.update", cmdPrefix)
	}

	_ = cmd.PersistentFlags().String(UpdateFlagName, "", "Optional json string for [update]. ")

	// add flags for body
	if err := registerModelContainerUpdateBodyFlags(0, "containerUpdateBody", cmd); err != nil {
		return err
	}

	return nil
}

func retrieveOperationContainerContainerUpdateIDFlag(m *container.ContainerUpdateParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("id") {

		var IDFlagName string
		if cmdPrefix == "" {
			IDFlagName = "id"
		} else {
			IDFlagName = fmt.Sprintf("%v.id", cmdPrefix)
		}

		IDFlagValue, err := cmd.Flags().GetString(IDFlagName)
		if err != nil {
			return err, false
		}
		m.ID = IDFlagValue

	}
	return nil, retAdded
}
func retrieveOperationContainerContainerUpdateUpdateFlag(m *container.ContainerUpdateParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("update") {
		// Read update string from cmd and unmarshal
		updateValueStr, err := cmd.Flags().GetString("update")
		if err != nil {
			return err, false
		}

		updateValue := container.ContainerUpdateBody{}
		if err := json.Unmarshal([]byte(updateValueStr), &updateValue); err != nil {
			return fmt.Errorf("cannot unmarshal update string in ContainerUpdateBody: %v", err), false
		}
		m.Update = updateValue
	}
	updateValueModel := m.Update
	if swag.IsZero(updateValueModel) {
		updateValueModel = container.ContainerUpdateBody{}
	}
	err, added := retrieveModelContainerUpdateBodyFlags(0, &updateValueModel, "containerUpdateBody", cmd)
	if err != nil {
		return err, false
	}
	if added {
		m.Update = updateValueModel
	}
	if dryRun && debug {

		updateValueDebugBytes, err := json.Marshal(m.Update)
		if err != nil {
			return err, false
		}
		logDebugf("Update dry-run payload: %v", string(updateValueDebugBytes))
	}
	retAdded = retAdded || added

	return nil, retAdded
}

// parseOperationContainerContainerUpdateResult parses request result and return the string content
func parseOperationContainerContainerUpdateResult(resp0 *container.ContainerUpdateOK, respErr error) (string, error) {
	if respErr != nil {

		var iResp0 interface{} = respErr
		resp0, ok := iResp0.(*container.ContainerUpdateOK)
		if ok {
			if !swag.IsZero(resp0) && !swag.IsZero(resp0.Payload) {
				msgStr, err := json.Marshal(resp0.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		var iResp1 interface{} = respErr
		resp1, ok := iResp1.(*container.ContainerUpdateNotFound)
		if ok {
			if !swag.IsZero(resp1) && !swag.IsZero(resp1.Payload) {
				msgStr, err := json.Marshal(resp1.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		var iResp2 interface{} = respErr
		resp2, ok := iResp2.(*container.ContainerUpdateInternalServerError)
		if ok {
			if !swag.IsZero(resp2) && !swag.IsZero(resp2.Payload) {
				msgStr, err := json.Marshal(resp2.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		return "", respErr
	}

	if !swag.IsZero(resp0) && !swag.IsZero(resp0.Payload) {
		msgStr, err := json.Marshal(resp0.Payload)
		if err != nil {
			return "", err
		}
		return string(msgStr), nil
	}

	return "", nil
}

// register flags to command
func registerModelContainerUpdateBodyFlags(depth int, cmdPrefix string, cmd *cobra.Command) error {

	// register embedded models.Resources flags

	if err := registerModelResourcesFlags(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	// register anonymous fields for ContainerUpdateParamsBodyAO1

	if err := registerContainerUpdateBodyAnonContainerUpdateParamsBodyAO1RestartPolicy(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	return nil
}

// inline definition name ContainerUpdateParamsBodyAO1, type

func registerContainerUpdateBodyAnonContainerUpdateParamsBodyAO1RestartPolicy(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	var RestartPolicyFlagName string
	if cmdPrefix == "" {
		RestartPolicyFlagName = "RestartPolicy"
	} else {
		RestartPolicyFlagName = fmt.Sprintf("%v.RestartPolicy", cmdPrefix)
	}

	if err := registerModelRestartPolicyFlags(depth+1, RestartPolicyFlagName, cmd); err != nil {
		return err
	}

	return nil
}

// retrieve flags from commands, and set value in model. Return true if any flag is passed by user to fill model field.
func retrieveModelContainerUpdateBodyFlags(depth int, m *container.ContainerUpdateBody, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false

	// retrieve model models.Resources
	err, ContainerUpdateParamsBodyAO0Added := retrieveModelResourcesFlags(depth, &m.Resources, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || ContainerUpdateParamsBodyAO0Added

	// retrieve allOf ContainerUpdateParamsBodyAO1 fields

	err, RestartPolicyAdded := retrieveContainerUpdateBodyAnonContainerUpdateParamsBodyAO1RestartPolicyFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || RestartPolicyAdded

	return nil, retAdded
}

// define retrieve functions for fields for inline definition name ContainerUpdateParamsBodyAO1

func retrieveContainerUpdateBodyAnonContainerUpdateParamsBodyAO1RestartPolicyFlags(depth int, m *container.ContainerUpdateBody, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	RestartPolicyFlagName := fmt.Sprintf("%v.RestartPolicy", cmdPrefix)
	if cmd.Flags().Changed(RestartPolicyFlagName) {
		// info: complex object RestartPolicy models.RestartPolicy is retrieved outside this Changed() block
	}
	RestartPolicyFlagValue := m.RestartPolicy
	if swag.IsZero(RestartPolicyFlagValue) {
		RestartPolicyFlagValue = &models.RestartPolicy{}
	}

	err, RestartPolicyAdded := retrieveModelRestartPolicyFlags(depth+1, RestartPolicyFlagValue, RestartPolicyFlagName, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || RestartPolicyAdded
	if RestartPolicyAdded {
		m.RestartPolicy = RestartPolicyFlagValue
	}

	return nil, retAdded
}

// register flags to command
func registerModelContainerUpdateOKBodyFlags(depth int, cmdPrefix string, cmd *cobra.Command) error {

	if err := registerContainerUpdateOKBodyWarnings(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	return nil
}

func registerContainerUpdateOKBodyWarnings(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	// warning: Warnings []string array type is not supported by go-swagger cli yet

	return nil
}

// retrieve flags from commands, and set value in model. Return true if any flag is passed by user to fill model field.
func retrieveModelContainerUpdateOKBodyFlags(depth int, m *container.ContainerUpdateOKBody, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false

	err, WarningsAdded := retrieveContainerUpdateOKBodyWarningsFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || WarningsAdded

	return nil, retAdded
}

func retrieveContainerUpdateOKBodyWarningsFlags(depth int, m *container.ContainerUpdateOKBody, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	WarningsFlagName := fmt.Sprintf("%v.Warnings", cmdPrefix)
	if cmd.Flags().Changed(WarningsFlagName) {
		// warning: Warnings array type []string is not supported by go-swagger cli yet
	}

	return nil, retAdded
}
