// Code generated by go-swagger; DO NOT EDIT.

package cli

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"

	"github.com/go-swagger/dockerctl/client/container"

	"github.com/go-openapi/swag"
	"github.com/spf13/cobra"
)

// makeOperationContainerContainerResizeCmd returns a cmd to handle operation containerResize
func makeOperationContainerContainerResizeCmd() (*cobra.Command, error) {
	cmd := &cobra.Command{
		Use:   "ContainerResize",
		Short: `Resize the TTY for a container.`,
		RunE:  runOperationContainerContainerResize,
	}

	if err := registerOperationContainerContainerResizeParamFlags(cmd); err != nil {
		return nil, err
	}

	return cmd, nil
}

// runOperationContainerContainerResize uses cmd flags to call endpoint api
func runOperationContainerContainerResize(cmd *cobra.Command, args []string) error {
	appCli, err := makeClient(cmd, args)
	if err != nil {
		return err
	}
	// retrieve flag values from cmd and fill params
	params := container.NewContainerResizeParams()
	if err, _ := retrieveOperationContainerContainerResizeHFlag(params, "", cmd); err != nil {
		return err
	}
	if err, _ := retrieveOperationContainerContainerResizeIDFlag(params, "", cmd); err != nil {
		return err
	}
	if err, _ := retrieveOperationContainerContainerResizeWFlag(params, "", cmd); err != nil {
		return err
	}
	if dryRun {

		logDebugf("dry-run flag specified. Skip sending request.")
		return nil
	}
	// make request and then print result
	msgStr, err := parseOperationContainerContainerResizeResult(appCli.Container.ContainerResize(params))
	if err != nil {
		return err
	}
	if !debug {

		fmt.Println(msgStr)
	}
	return nil
}

// registerOperationContainerContainerResizeParamFlags registers all flags needed to fill params
func registerOperationContainerContainerResizeParamFlags(cmd *cobra.Command) error {
	if err := registerOperationContainerContainerResizeHParamFlags("", cmd); err != nil {
		return err
	}
	if err := registerOperationContainerContainerResizeIDParamFlags("", cmd); err != nil {
		return err
	}
	if err := registerOperationContainerContainerResizeWParamFlags("", cmd); err != nil {
		return err
	}
	return nil
}

func registerOperationContainerContainerResizeHParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	HDescription := `Height of the tty session in characters`

	var HFlagName string
	if cmdPrefix == "" {
		HFlagName = "h"
	} else {
		HFlagName = fmt.Sprintf("%v.h", cmdPrefix)
	}

	var HFlagDefault int64

	_ = cmd.PersistentFlags().Int64(HFlagName, HFlagDefault, HDescription)

	return nil
}
func registerOperationContainerContainerResizeIDParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	IDDescription := `Required. ID or name of the container`

	var IDFlagName string
	if cmdPrefix == "" {
		IDFlagName = "id"
	} else {
		IDFlagName = fmt.Sprintf("%v.id", cmdPrefix)
	}

	var IDFlagDefault string

	_ = cmd.PersistentFlags().String(IDFlagName, IDFlagDefault, IDDescription)

	return nil
}
func registerOperationContainerContainerResizeWParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	WDescription := `Width of the tty session in characters`

	var WFlagName string
	if cmdPrefix == "" {
		WFlagName = "w"
	} else {
		WFlagName = fmt.Sprintf("%v.w", cmdPrefix)
	}

	var WFlagDefault int64

	_ = cmd.PersistentFlags().Int64(WFlagName, WFlagDefault, WDescription)

	return nil
}

func retrieveOperationContainerContainerResizeHFlag(m *container.ContainerResizeParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("h") {

		var HFlagName string
		if cmdPrefix == "" {
			HFlagName = "h"
		} else {
			HFlagName = fmt.Sprintf("%v.h", cmdPrefix)
		}

		HFlagValue, err := cmd.Flags().GetInt64(HFlagName)
		if err != nil {
			return err, false
		}
		m.H = &HFlagValue

	}
	return nil, retAdded
}
func retrieveOperationContainerContainerResizeIDFlag(m *container.ContainerResizeParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("id") {

		var IDFlagName string
		if cmdPrefix == "" {
			IDFlagName = "id"
		} else {
			IDFlagName = fmt.Sprintf("%v.id", cmdPrefix)
		}

		IDFlagValue, err := cmd.Flags().GetString(IDFlagName)
		if err != nil {
			return err, false
		}
		m.ID = IDFlagValue

	}
	return nil, retAdded
}
func retrieveOperationContainerContainerResizeWFlag(m *container.ContainerResizeParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("w") {

		var WFlagName string
		if cmdPrefix == "" {
			WFlagName = "w"
		} else {
			WFlagName = fmt.Sprintf("%v.w", cmdPrefix)
		}

		WFlagValue, err := cmd.Flags().GetInt64(WFlagName)
		if err != nil {
			return err, false
		}
		m.W = &WFlagValue

	}
	return nil, retAdded
}

// parseOperationContainerContainerResizeResult parses request result and return the string content
func parseOperationContainerContainerResizeResult(resp0 *container.ContainerResizeOK, respErr error) (string, error) {
	if respErr != nil {

		// Non schema case: warning containerResizeOK is not supported

		var iResp1 interface{} = respErr
		resp1, ok := iResp1.(*container.ContainerResizeNotFound)
		if ok {
			if !swag.IsZero(resp1) && !swag.IsZero(resp1.Payload) {
				msgStr, err := json.Marshal(resp1.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		var iResp2 interface{} = respErr
		resp2, ok := iResp2.(*container.ContainerResizeInternalServerError)
		if ok {
			if !swag.IsZero(resp2) && !swag.IsZero(resp2.Payload) {
				msgStr, err := json.Marshal(resp2.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		return "", respErr
	}

	// warning: non schema response containerResizeOK is not supported by go-swagger cli yet.

	return "", nil
}
