// Code generated by go-swagger; DO NOT EDIT.

package cli

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"

	"github.com/go-swagger/dockerctl/client/container"

	"github.com/go-openapi/swag"
	"github.com/spf13/cobra"
)

// makeOperationContainerContainerStopCmd returns a cmd to handle operation containerStop
func makeOperationContainerContainerStopCmd() (*cobra.Command, error) {
	cmd := &cobra.Command{
		Use:   "ContainerStop",
		Short: ``,
		RunE:  runOperationContainerContainerStop,
	}

	if err := registerOperationContainerContainerStopParamFlags(cmd); err != nil {
		return nil, err
	}

	return cmd, nil
}

// runOperationContainerContainerStop uses cmd flags to call endpoint api
func runOperationContainerContainerStop(cmd *cobra.Command, args []string) error {
	appCli, err := makeClient(cmd, args)
	if err != nil {
		return err
	}
	// retrieve flag values from cmd and fill params
	params := container.NewContainerStopParams()
	if err, _ := retrieveOperationContainerContainerStopIDFlag(params, "", cmd); err != nil {
		return err
	}
	if err, _ := retrieveOperationContainerContainerStopTFlag(params, "", cmd); err != nil {
		return err
	}
	if dryRun {

		logDebugf("dry-run flag specified. Skip sending request.")
		return nil
	}
	// make request and then print result
	msgStr, err := parseOperationContainerContainerStopResult(appCli.Container.ContainerStop(params))
	if err != nil {
		return err
	}
	if !debug {

		fmt.Println(msgStr)
	}
	return nil
}

// registerOperationContainerContainerStopParamFlags registers all flags needed to fill params
func registerOperationContainerContainerStopParamFlags(cmd *cobra.Command) error {
	if err := registerOperationContainerContainerStopIDParamFlags("", cmd); err != nil {
		return err
	}
	if err := registerOperationContainerContainerStopTParamFlags("", cmd); err != nil {
		return err
	}
	return nil
}

func registerOperationContainerContainerStopIDParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	IDDescription := `Required. ID or name of the container`

	var IDFlagName string
	if cmdPrefix == "" {
		IDFlagName = "id"
	} else {
		IDFlagName = fmt.Sprintf("%v.id", cmdPrefix)
	}

	var IDFlagDefault string

	_ = cmd.PersistentFlags().String(IDFlagName, IDFlagDefault, IDDescription)

	return nil
}
func registerOperationContainerContainerStopTParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	TDescription := `Number of seconds to wait before killing the container`

	var TFlagName string
	if cmdPrefix == "" {
		TFlagName = "t"
	} else {
		TFlagName = fmt.Sprintf("%v.t", cmdPrefix)
	}

	var TFlagDefault int64

	_ = cmd.PersistentFlags().Int64(TFlagName, TFlagDefault, TDescription)

	return nil
}

func retrieveOperationContainerContainerStopIDFlag(m *container.ContainerStopParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("id") {

		var IDFlagName string
		if cmdPrefix == "" {
			IDFlagName = "id"
		} else {
			IDFlagName = fmt.Sprintf("%v.id", cmdPrefix)
		}

		IDFlagValue, err := cmd.Flags().GetString(IDFlagName)
		if err != nil {
			return err, false
		}
		m.ID = IDFlagValue

	}
	return nil, retAdded
}
func retrieveOperationContainerContainerStopTFlag(m *container.ContainerStopParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("t") {

		var TFlagName string
		if cmdPrefix == "" {
			TFlagName = "t"
		} else {
			TFlagName = fmt.Sprintf("%v.t", cmdPrefix)
		}

		TFlagValue, err := cmd.Flags().GetInt64(TFlagName)
		if err != nil {
			return err, false
		}
		m.T = &TFlagValue

	}
	return nil, retAdded
}

// parseOperationContainerContainerStopResult parses request result and return the string content
func parseOperationContainerContainerStopResult(resp0 *container.ContainerStopNoContent, respErr error) (string, error) {
	if respErr != nil {

		// Non schema case: warning containerStopNoContent is not supported

		// Non schema case: warning containerStopNotModified is not supported

		var iResp2 interface{} = respErr
		resp2, ok := iResp2.(*container.ContainerStopNotFound)
		if ok {
			if !swag.IsZero(resp2) && !swag.IsZero(resp2.Payload) {
				msgStr, err := json.Marshal(resp2.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		var iResp3 interface{} = respErr
		resp3, ok := iResp3.(*container.ContainerStopInternalServerError)
		if ok {
			if !swag.IsZero(resp3) && !swag.IsZero(resp3.Payload) {
				msgStr, err := json.Marshal(resp3.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		return "", respErr
	}

	// warning: non schema response containerStopNoContent is not supported by go-swagger cli yet.

	return "", nil
}
