// Code generated by go-swagger; DO NOT EDIT.

package cli

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"

	"github.com/go-swagger/dockerctl/client/service"

	"github.com/go-openapi/swag"
	"github.com/spf13/cobra"
)

// makeOperationServiceServiceCreateCmd returns a cmd to handle operation serviceCreate
func makeOperationServiceServiceCreateCmd() (*cobra.Command, error) {
	cmd := &cobra.Command{
		Use:   "ServiceCreate",
		Short: ``,
		RunE:  runOperationServiceServiceCreate,
	}

	if err := registerOperationServiceServiceCreateParamFlags(cmd); err != nil {
		return nil, err
	}

	return cmd, nil
}

// runOperationServiceServiceCreate uses cmd flags to call endpoint api
func runOperationServiceServiceCreate(cmd *cobra.Command, args []string) error {
	appCli, err := makeClient(cmd, args)
	if err != nil {
		return err
	}
	// retrieve flag values from cmd and fill params
	params := service.NewServiceCreateParams()
	if err, _ := retrieveOperationServiceServiceCreateXRegistryAuthFlag(params, "", cmd); err != nil {
		return err
	}
	if err, _ := retrieveOperationServiceServiceCreateBodyFlag(params, "", cmd); err != nil {
		return err
	}
	if dryRun {

		logDebugf("dry-run flag specified. Skip sending request.")
		return nil
	}
	// make request and then print result
	msgStr, err := parseOperationServiceServiceCreateResult(appCli.Service.ServiceCreate(params))
	if err != nil {
		return err
	}
	if !debug {

		fmt.Println(msgStr)
	}
	return nil
}

// registerOperationServiceServiceCreateParamFlags registers all flags needed to fill params
func registerOperationServiceServiceCreateParamFlags(cmd *cobra.Command) error {
	if err := registerOperationServiceServiceCreateXRegistryAuthParamFlags("", cmd); err != nil {
		return err
	}
	if err := registerOperationServiceServiceCreateBodyParamFlags("", cmd); err != nil {
		return err
	}
	return nil
}

func registerOperationServiceServiceCreateXRegistryAuthParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	XRegistryAuthDescription := `A base64-encoded auth configuration for pulling from private registries. [See the authentication section for details.](#section/Authentication)`

	var XRegistryAuthFlagName string
	if cmdPrefix == "" {
		XRegistryAuthFlagName = "X-Registry-Auth"
	} else {
		XRegistryAuthFlagName = fmt.Sprintf("%v.X-Registry-Auth", cmdPrefix)
	}

	var XRegistryAuthFlagDefault string

	_ = cmd.PersistentFlags().String(XRegistryAuthFlagName, XRegistryAuthFlagDefault, XRegistryAuthDescription)

	return nil
}
func registerOperationServiceServiceCreateBodyParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	var BodyFlagName string
	if cmdPrefix == "" {
		BodyFlagName = "body"
	} else {
		BodyFlagName = fmt.Sprintf("%v.body", cmdPrefix)
	}

	_ = cmd.PersistentFlags().String(BodyFlagName, "", "Optional json string for [body]. ")

	// add flags for body
	if err := registerModelServiceCreateBodyFlags(0, "serviceCreateBody", cmd); err != nil {
		return err
	}

	return nil
}

func retrieveOperationServiceServiceCreateXRegistryAuthFlag(m *service.ServiceCreateParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("X-Registry-Auth") {

		var XRegistryAuthFlagName string
		if cmdPrefix == "" {
			XRegistryAuthFlagName = "X-Registry-Auth"
		} else {
			XRegistryAuthFlagName = fmt.Sprintf("%v.X-Registry-Auth", cmdPrefix)
		}

		XRegistryAuthFlagValue, err := cmd.Flags().GetString(XRegistryAuthFlagName)
		if err != nil {
			return err, false
		}
		m.XRegistryAuth = &XRegistryAuthFlagValue

	}
	return nil, retAdded
}
func retrieveOperationServiceServiceCreateBodyFlag(m *service.ServiceCreateParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("body") {
		// Read body string from cmd and unmarshal
		bodyValueStr, err := cmd.Flags().GetString("body")
		if err != nil {
			return err, false
		}

		bodyValue := service.ServiceCreateBody{}
		if err := json.Unmarshal([]byte(bodyValueStr), &bodyValue); err != nil {
			return fmt.Errorf("cannot unmarshal body string in ServiceCreateBody: %v", err), false
		}
		m.Body = bodyValue
	}
	bodyValueModel := m.Body
	if swag.IsZero(bodyValueModel) {
		bodyValueModel = service.ServiceCreateBody{}
	}
	err, added := retrieveModelServiceCreateBodyFlags(0, &bodyValueModel, "serviceCreateBody", cmd)
	if err != nil {
		return err, false
	}
	if added {
		m.Body = bodyValueModel
	}
	if dryRun && debug {

		bodyValueDebugBytes, err := json.Marshal(m.Body)
		if err != nil {
			return err, false
		}
		logDebugf("Body dry-run payload: %v", string(bodyValueDebugBytes))
	}
	retAdded = retAdded || added

	return nil, retAdded
}

// parseOperationServiceServiceCreateResult parses request result and return the string content
func parseOperationServiceServiceCreateResult(resp0 *service.ServiceCreateCreated, respErr error) (string, error) {
	if respErr != nil {

		var iResp0 interface{} = respErr
		resp0, ok := iResp0.(*service.ServiceCreateCreated)
		if ok {
			if !swag.IsZero(resp0) && !swag.IsZero(resp0.Payload) {
				msgStr, err := json.Marshal(resp0.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		var iResp1 interface{} = respErr
		resp1, ok := iResp1.(*service.ServiceCreateBadRequest)
		if ok {
			if !swag.IsZero(resp1) && !swag.IsZero(resp1.Payload) {
				msgStr, err := json.Marshal(resp1.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		var iResp2 interface{} = respErr
		resp2, ok := iResp2.(*service.ServiceCreateForbidden)
		if ok {
			if !swag.IsZero(resp2) && !swag.IsZero(resp2.Payload) {
				msgStr, err := json.Marshal(resp2.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		var iResp3 interface{} = respErr
		resp3, ok := iResp3.(*service.ServiceCreateConflict)
		if ok {
			if !swag.IsZero(resp3) && !swag.IsZero(resp3.Payload) {
				msgStr, err := json.Marshal(resp3.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		var iResp4 interface{} = respErr
		resp4, ok := iResp4.(*service.ServiceCreateInternalServerError)
		if ok {
			if !swag.IsZero(resp4) && !swag.IsZero(resp4.Payload) {
				msgStr, err := json.Marshal(resp4.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		var iResp5 interface{} = respErr
		resp5, ok := iResp5.(*service.ServiceCreateServiceUnavailable)
		if ok {
			if !swag.IsZero(resp5) && !swag.IsZero(resp5.Payload) {
				msgStr, err := json.Marshal(resp5.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		return "", respErr
	}

	if !swag.IsZero(resp0) && !swag.IsZero(resp0.Payload) {
		msgStr, err := json.Marshal(resp0.Payload)
		if err != nil {
			return "", err
		}
		return string(msgStr), nil
	}

	return "", nil
}

// register flags to command
func registerModelServiceCreateBodyFlags(depth int, cmdPrefix string, cmd *cobra.Command) error {

	// register embedded models.ServiceSpec flags

	if err := registerModelServiceSpecFlags(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	// ServiceCreateParamsBodyAO1 ServiceCreateParamsBodyAllOf1 register is skipped

	return nil
}

// retrieve flags from commands, and set value in model. Return true if any flag is passed by user to fill model field.
func retrieveModelServiceCreateBodyFlags(depth int, m *service.ServiceCreateBody, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false

	// retrieve model models.ServiceSpec
	err, ServiceCreateParamsBodyAO0Added := retrieveModelServiceSpecFlags(depth, &m.ServiceSpec, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || ServiceCreateParamsBodyAO0Added

	return nil, retAdded
}

// register flags to command
func registerModelServiceCreateCreatedBodyFlags(depth int, cmdPrefix string, cmd *cobra.Command) error {

	if err := registerServiceCreateCreatedBodyID(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerServiceCreateCreatedBodyWarning(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	return nil
}

func registerServiceCreateCreatedBodyID(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	IDDescription := `The ID of the created service.`

	var IDFlagName string
	if cmdPrefix == "" {
		IDFlagName = "ID"
	} else {
		IDFlagName = fmt.Sprintf("%v.ID", cmdPrefix)
	}

	var IDFlagDefault string

	_ = cmd.PersistentFlags().String(IDFlagName, IDFlagDefault, IDDescription)

	return nil
}

func registerServiceCreateCreatedBodyWarning(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	WarningDescription := `Optional warning message`

	var WarningFlagName string
	if cmdPrefix == "" {
		WarningFlagName = "Warning"
	} else {
		WarningFlagName = fmt.Sprintf("%v.Warning", cmdPrefix)
	}

	var WarningFlagDefault string

	_ = cmd.PersistentFlags().String(WarningFlagName, WarningFlagDefault, WarningDescription)

	return nil
}

// retrieve flags from commands, and set value in model. Return true if any flag is passed by user to fill model field.
func retrieveModelServiceCreateCreatedBodyFlags(depth int, m *service.ServiceCreateCreatedBody, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false

	err, IDAdded := retrieveServiceCreateCreatedBodyIDFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || IDAdded

	err, WarningAdded := retrieveServiceCreateCreatedBodyWarningFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || WarningAdded

	return nil, retAdded
}

func retrieveServiceCreateCreatedBodyIDFlags(depth int, m *service.ServiceCreateCreatedBody, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	IDFlagName := fmt.Sprintf("%v.ID", cmdPrefix)
	if cmd.Flags().Changed(IDFlagName) {

		var IDFlagName string
		if cmdPrefix == "" {
			IDFlagName = "ID"
		} else {
			IDFlagName = fmt.Sprintf("%v.ID", cmdPrefix)
		}

		IDFlagValue, err := cmd.Flags().GetString(IDFlagName)
		if err != nil {
			return err, false
		}
		m.ID = IDFlagValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveServiceCreateCreatedBodyWarningFlags(depth int, m *service.ServiceCreateCreatedBody, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	WarningFlagName := fmt.Sprintf("%v.Warning", cmdPrefix)
	if cmd.Flags().Changed(WarningFlagName) {

		var WarningFlagName string
		if cmdPrefix == "" {
			WarningFlagName = "Warning"
		} else {
			WarningFlagName = fmt.Sprintf("%v.Warning", cmdPrefix)
		}

		WarningFlagValue, err := cmd.Flags().GetString(WarningFlagName)
		if err != nil {
			return err, false
		}
		m.Warning = WarningFlagValue

		retAdded = true
	}

	return nil, retAdded
}

// Name: [ServiceCreateParamsBodyAllOf1], Type:[interface{}], register and retrieve functions are not rendered by go-swagger cli
