// Code generated by go-swagger; DO NOT EDIT.

package cli

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-swagger/dockerctl/models"
	"github.com/spf13/cobra"
)

// Schema cli for ServiceSpec

// register flags to command
func registerModelServiceSpecFlags(depth int, cmdPrefix string, cmd *cobra.Command) error {

	if err := registerServiceSpecEndpointSpec(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerServiceSpecLabels(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerServiceSpecMode(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerServiceSpecName(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerServiceSpecNetworks(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerServiceSpecRollbackConfig(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerServiceSpecTaskTemplate(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerServiceSpecUpdateConfig(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	return nil
}

func registerServiceSpecEndpointSpec(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	var endpointSpecFlagName string
	if cmdPrefix == "" {
		endpointSpecFlagName = "EndpointSpec"
	} else {
		endpointSpecFlagName = fmt.Sprintf("%v.EndpointSpec", cmdPrefix)
	}

	if err := registerModelEndpointSpecFlags(depth+1, endpointSpecFlagName, cmd); err != nil {
		return err
	}

	return nil
}

func registerServiceSpecLabels(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	// warning: Labels map[string]string map type is not supported by go-swagger cli yet

	return nil
}

func registerServiceSpecMode(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	var modeFlagName string
	if cmdPrefix == "" {
		modeFlagName = "Mode"
	} else {
		modeFlagName = fmt.Sprintf("%v.Mode", cmdPrefix)
	}

	if err := registerModelServiceSpecModeFlags(depth+1, modeFlagName, cmd); err != nil {
		return err
	}

	return nil
}

func registerServiceSpecName(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	nameDescription := `Name of the service.`

	var nameFlagName string
	if cmdPrefix == "" {
		nameFlagName = "Name"
	} else {
		nameFlagName = fmt.Sprintf("%v.Name", cmdPrefix)
	}

	var nameFlagDefault string

	_ = cmd.PersistentFlags().String(nameFlagName, nameFlagDefault, nameDescription)

	return nil
}

func registerServiceSpecNetworks(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	// warning: Networks []*NetworkAttachmentConfig array type is not supported by go-swagger cli yet

	return nil
}

func registerServiceSpecRollbackConfig(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	var rollbackConfigFlagName string
	if cmdPrefix == "" {
		rollbackConfigFlagName = "RollbackConfig"
	} else {
		rollbackConfigFlagName = fmt.Sprintf("%v.RollbackConfig", cmdPrefix)
	}

	if err := registerModelServiceSpecRollbackConfigFlags(depth+1, rollbackConfigFlagName, cmd); err != nil {
		return err
	}

	return nil
}

func registerServiceSpecTaskTemplate(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	var taskTemplateFlagName string
	if cmdPrefix == "" {
		taskTemplateFlagName = "TaskTemplate"
	} else {
		taskTemplateFlagName = fmt.Sprintf("%v.TaskTemplate", cmdPrefix)
	}

	if err := registerModelTaskSpecFlags(depth+1, taskTemplateFlagName, cmd); err != nil {
		return err
	}

	return nil
}

func registerServiceSpecUpdateConfig(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	var updateConfigFlagName string
	if cmdPrefix == "" {
		updateConfigFlagName = "UpdateConfig"
	} else {
		updateConfigFlagName = fmt.Sprintf("%v.UpdateConfig", cmdPrefix)
	}

	if err := registerModelServiceSpecUpdateConfigFlags(depth+1, updateConfigFlagName, cmd); err != nil {
		return err
	}

	return nil
}

// retrieve flags from commands, and set value in model. Return true if any flag is passed by user to fill model field.
func retrieveModelServiceSpecFlags(depth int, m *models.ServiceSpec, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false

	err, endpointSpecAdded := retrieveServiceSpecEndpointSpecFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || endpointSpecAdded

	err, labelsAdded := retrieveServiceSpecLabelsFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || labelsAdded

	err, modeAdded := retrieveServiceSpecModeFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || modeAdded

	err, nameAdded := retrieveServiceSpecNameFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || nameAdded

	err, networksAdded := retrieveServiceSpecNetworksFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || networksAdded

	err, rollbackConfigAdded := retrieveServiceSpecRollbackConfigFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || rollbackConfigAdded

	err, taskTemplateAdded := retrieveServiceSpecTaskTemplateFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || taskTemplateAdded

	err, updateConfigAdded := retrieveServiceSpecUpdateConfigFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || updateConfigAdded

	return nil, retAdded
}

func retrieveServiceSpecEndpointSpecFlags(depth int, m *models.ServiceSpec, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	endpointSpecFlagName := fmt.Sprintf("%v.EndpointSpec", cmdPrefix)
	if cmd.Flags().Changed(endpointSpecFlagName) {

		endpointSpecFlagValue := models.EndpointSpec{}
		err, added := retrieveModelEndpointSpecFlags(depth+1, &endpointSpecFlagValue, endpointSpecFlagName, cmd)
		if err != nil {
			return err, false
		}
		retAdded = retAdded || added
		if added {
			m.EndpointSpec = &endpointSpecFlagValue
		}
	}

	return nil, retAdded
}

func retrieveServiceSpecLabelsFlags(depth int, m *models.ServiceSpec, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	labelsFlagName := fmt.Sprintf("%v.Labels", cmdPrefix)
	if cmd.Flags().Changed(labelsFlagName) {
		// warning: Labels map type map[string]string is not supported by go-swagger cli yet
	}

	return nil, retAdded
}

func retrieveServiceSpecModeFlags(depth int, m *models.ServiceSpec, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	modeFlagName := fmt.Sprintf("%v.Mode", cmdPrefix)
	if cmd.Flags().Changed(modeFlagName) {

		modeFlagValue := models.ServiceSpecMode{}
		err, added := retrieveModelServiceSpecModeFlags(depth+1, &modeFlagValue, modeFlagName, cmd)
		if err != nil {
			return err, false
		}
		retAdded = retAdded || added
		if added {
			m.Mode = &modeFlagValue
		}
	}

	return nil, retAdded
}

func retrieveServiceSpecNameFlags(depth int, m *models.ServiceSpec, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	nameFlagName := fmt.Sprintf("%v.Name", cmdPrefix)
	if cmd.Flags().Changed(nameFlagName) {

		var nameFlagName string
		if cmdPrefix == "" {
			nameFlagName = "Name"
		} else {
			nameFlagName = fmt.Sprintf("%v.Name", cmdPrefix)
		}

		nameFlagValue, err := cmd.Flags().GetString(nameFlagName)
		if err != nil {
			return err, false
		}
		m.Name = nameFlagValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveServiceSpecNetworksFlags(depth int, m *models.ServiceSpec, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	networksFlagName := fmt.Sprintf("%v.Networks", cmdPrefix)
	if cmd.Flags().Changed(networksFlagName) {
		// warning: Networks array type []*NetworkAttachmentConfig is not supported by go-swagger cli yet
	}

	return nil, retAdded
}

func retrieveServiceSpecRollbackConfigFlags(depth int, m *models.ServiceSpec, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	rollbackConfigFlagName := fmt.Sprintf("%v.RollbackConfig", cmdPrefix)
	if cmd.Flags().Changed(rollbackConfigFlagName) {

		rollbackConfigFlagValue := models.ServiceSpecRollbackConfig{}
		err, added := retrieveModelServiceSpecRollbackConfigFlags(depth+1, &rollbackConfigFlagValue, rollbackConfigFlagName, cmd)
		if err != nil {
			return err, false
		}
		retAdded = retAdded || added
		if added {
			m.RollbackConfig = &rollbackConfigFlagValue
		}
	}

	return nil, retAdded
}

func retrieveServiceSpecTaskTemplateFlags(depth int, m *models.ServiceSpec, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	taskTemplateFlagName := fmt.Sprintf("%v.TaskTemplate", cmdPrefix)
	if cmd.Flags().Changed(taskTemplateFlagName) {

		taskTemplateFlagValue := models.TaskSpec{}
		err, added := retrieveModelTaskSpecFlags(depth+1, &taskTemplateFlagValue, taskTemplateFlagName, cmd)
		if err != nil {
			return err, false
		}
		retAdded = retAdded || added
		if added {
			m.TaskTemplate = &taskTemplateFlagValue
		}
	}

	return nil, retAdded
}

func retrieveServiceSpecUpdateConfigFlags(depth int, m *models.ServiceSpec, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	updateConfigFlagName := fmt.Sprintf("%v.UpdateConfig", cmdPrefix)
	if cmd.Flags().Changed(updateConfigFlagName) {

		updateConfigFlagValue := models.ServiceSpecUpdateConfig{}
		err, added := retrieveModelServiceSpecUpdateConfigFlags(depth+1, &updateConfigFlagValue, updateConfigFlagName, cmd)
		if err != nil {
			return err, false
		}
		retAdded = retAdded || added
		if added {
			m.UpdateConfig = &updateConfigFlagValue
		}
	}

	return nil, retAdded
}

// Extra schema cli for ServiceSpecMode

// register flags to command
func registerModelServiceSpecModeFlags(depth int, cmdPrefix string, cmd *cobra.Command) error {

	if err := registerServiceSpecModeGlobal(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerServiceSpecModeReplicated(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	return nil
}

func registerServiceSpecModeGlobal(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	// warning: Global interface{} map type is not supported by go-swagger cli yet

	return nil
}

func registerServiceSpecModeReplicated(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	var replicatedFlagName string
	if cmdPrefix == "" {
		replicatedFlagName = "Replicated"
	} else {
		replicatedFlagName = fmt.Sprintf("%v.Replicated", cmdPrefix)
	}

	if err := registerModelServiceSpecModeReplicatedFlags(depth+1, replicatedFlagName, cmd); err != nil {
		return err
	}

	return nil
}

// retrieve flags from commands, and set value in model. Return true if any flag is passed by user to fill model field.
func retrieveModelServiceSpecModeFlags(depth int, m *models.ServiceSpecMode, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false

	err, globalAdded := retrieveServiceSpecModeGlobalFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || globalAdded

	err, replicatedAdded := retrieveServiceSpecModeReplicatedFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || replicatedAdded

	return nil, retAdded
}

func retrieveServiceSpecModeGlobalFlags(depth int, m *models.ServiceSpecMode, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	globalFlagName := fmt.Sprintf("%v.Global", cmdPrefix)
	if cmd.Flags().Changed(globalFlagName) {
		// warning: Global map type interface{} is not supported by go-swagger cli yet
	}

	return nil, retAdded
}

func retrieveServiceSpecModeReplicatedFlags(depth int, m *models.ServiceSpecMode, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	replicatedFlagName := fmt.Sprintf("%v.Replicated", cmdPrefix)
	if cmd.Flags().Changed(replicatedFlagName) {

		replicatedFlagValue := models.ServiceSpecModeReplicated{}
		err, added := retrieveModelServiceSpecModeReplicatedFlags(depth+1, &replicatedFlagValue, replicatedFlagName, cmd)
		if err != nil {
			return err, false
		}
		retAdded = retAdded || added
		if added {
			m.Replicated = &replicatedFlagValue
		}
	}

	return nil, retAdded
}

// Extra schema cli for ServiceSpecModeReplicated

// register flags to command
func registerModelServiceSpecModeReplicatedFlags(depth int, cmdPrefix string, cmd *cobra.Command) error {

	if err := registerServiceSpecModeReplicatedReplicas(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	return nil
}

func registerServiceSpecModeReplicatedReplicas(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	replicasDescription := ``

	var replicasFlagName string
	if cmdPrefix == "" {
		replicasFlagName = "Replicas"
	} else {
		replicasFlagName = fmt.Sprintf("%v.Replicas", cmdPrefix)
	}

	var replicasFlagDefault int64

	_ = cmd.PersistentFlags().Int64(replicasFlagName, replicasFlagDefault, replicasDescription)

	return nil
}

// retrieve flags from commands, and set value in model. Return true if any flag is passed by user to fill model field.
func retrieveModelServiceSpecModeReplicatedFlags(depth int, m *models.ServiceSpecModeReplicated, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false

	err, replicasAdded := retrieveServiceSpecModeReplicatedReplicasFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || replicasAdded

	return nil, retAdded
}

func retrieveServiceSpecModeReplicatedReplicasFlags(depth int, m *models.ServiceSpecModeReplicated, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	replicasFlagName := fmt.Sprintf("%v.Replicas", cmdPrefix)
	if cmd.Flags().Changed(replicasFlagName) {

		var replicasFlagName string
		if cmdPrefix == "" {
			replicasFlagName = "Replicas"
		} else {
			replicasFlagName = fmt.Sprintf("%v.Replicas", cmdPrefix)
		}

		replicasFlagValue, err := cmd.Flags().GetInt64(replicasFlagName)
		if err != nil {
			return err, false
		}
		m.Replicas = replicasFlagValue

		retAdded = true
	}

	return nil, retAdded
}

// Extra schema cli for ServiceSpecRollbackConfig

// register flags to command
func registerModelServiceSpecRollbackConfigFlags(depth int, cmdPrefix string, cmd *cobra.Command) error {

	if err := registerServiceSpecRollbackConfigDelay(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerServiceSpecRollbackConfigFailureAction(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerServiceSpecRollbackConfigMaxFailureRatio(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerServiceSpecRollbackConfigMonitor(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerServiceSpecRollbackConfigOrder(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerServiceSpecRollbackConfigParallelism(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	return nil
}

func registerServiceSpecRollbackConfigDelay(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	delayDescription := `Amount of time between rollback iterations, in nanoseconds.`

	var delayFlagName string
	if cmdPrefix == "" {
		delayFlagName = "Delay"
	} else {
		delayFlagName = fmt.Sprintf("%v.Delay", cmdPrefix)
	}

	var delayFlagDefault int64

	_ = cmd.PersistentFlags().Int64(delayFlagName, delayFlagDefault, delayDescription)

	return nil
}

func registerServiceSpecRollbackConfigFailureAction(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	failureActionDescription := `Action to take if an rolled back task fails to run, or stops running during the rollback.`

	var failureActionFlagName string
	if cmdPrefix == "" {
		failureActionFlagName = "FailureAction"
	} else {
		failureActionFlagName = fmt.Sprintf("%v.FailureAction", cmdPrefix)
	}

	var failureActionFlagDefault string

	_ = cmd.PersistentFlags().String(failureActionFlagName, failureActionFlagDefault, failureActionDescription)

	return nil
}

func registerServiceSpecRollbackConfigMaxFailureRatio(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	maxFailureRatioDescription := `The fraction of tasks that may fail during a rollback before the failure action is invoked, specified as a floating point number between 0 and 1.`

	var maxFailureRatioFlagName string
	if cmdPrefix == "" {
		maxFailureRatioFlagName = "MaxFailureRatio"
	} else {
		maxFailureRatioFlagName = fmt.Sprintf("%v.MaxFailureRatio", cmdPrefix)
	}

	var maxFailureRatioFlagDefault float64

	_ = cmd.PersistentFlags().Float64(maxFailureRatioFlagName, maxFailureRatioFlagDefault, maxFailureRatioDescription)

	return nil
}

func registerServiceSpecRollbackConfigMonitor(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	monitorDescription := `Amount of time to monitor each rolled back task for failures, in nanoseconds.`

	var monitorFlagName string
	if cmdPrefix == "" {
		monitorFlagName = "Monitor"
	} else {
		monitorFlagName = fmt.Sprintf("%v.Monitor", cmdPrefix)
	}

	var monitorFlagDefault int64

	_ = cmd.PersistentFlags().Int64(monitorFlagName, monitorFlagDefault, monitorDescription)

	return nil
}

func registerServiceSpecRollbackConfigOrder(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	orderDescription := `The order of operations when rolling back a task. Either the old task is shut down before the new task is started, or the new task is started before the old task is shut down.`

	var orderFlagName string
	if cmdPrefix == "" {
		orderFlagName = "Order"
	} else {
		orderFlagName = fmt.Sprintf("%v.Order", cmdPrefix)
	}

	var orderFlagDefault string

	_ = cmd.PersistentFlags().String(orderFlagName, orderFlagDefault, orderDescription)

	return nil
}

func registerServiceSpecRollbackConfigParallelism(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	parallelismDescription := `Maximum number of tasks to be rolled back in one iteration (0 means unlimited parallelism).`

	var parallelismFlagName string
	if cmdPrefix == "" {
		parallelismFlagName = "Parallelism"
	} else {
		parallelismFlagName = fmt.Sprintf("%v.Parallelism", cmdPrefix)
	}

	var parallelismFlagDefault int64

	_ = cmd.PersistentFlags().Int64(parallelismFlagName, parallelismFlagDefault, parallelismDescription)

	return nil
}

// retrieve flags from commands, and set value in model. Return true if any flag is passed by user to fill model field.
func retrieveModelServiceSpecRollbackConfigFlags(depth int, m *models.ServiceSpecRollbackConfig, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false

	err, delayAdded := retrieveServiceSpecRollbackConfigDelayFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || delayAdded

	err, failureActionAdded := retrieveServiceSpecRollbackConfigFailureActionFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || failureActionAdded

	err, maxFailureRatioAdded := retrieveServiceSpecRollbackConfigMaxFailureRatioFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || maxFailureRatioAdded

	err, monitorAdded := retrieveServiceSpecRollbackConfigMonitorFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || monitorAdded

	err, orderAdded := retrieveServiceSpecRollbackConfigOrderFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || orderAdded

	err, parallelismAdded := retrieveServiceSpecRollbackConfigParallelismFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || parallelismAdded

	return nil, retAdded
}

func retrieveServiceSpecRollbackConfigDelayFlags(depth int, m *models.ServiceSpecRollbackConfig, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	delayFlagName := fmt.Sprintf("%v.Delay", cmdPrefix)
	if cmd.Flags().Changed(delayFlagName) {

		var delayFlagName string
		if cmdPrefix == "" {
			delayFlagName = "Delay"
		} else {
			delayFlagName = fmt.Sprintf("%v.Delay", cmdPrefix)
		}

		delayFlagValue, err := cmd.Flags().GetInt64(delayFlagName)
		if err != nil {
			return err, false
		}
		m.Delay = delayFlagValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveServiceSpecRollbackConfigFailureActionFlags(depth int, m *models.ServiceSpecRollbackConfig, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	failureActionFlagName := fmt.Sprintf("%v.FailureAction", cmdPrefix)
	if cmd.Flags().Changed(failureActionFlagName) {

		var failureActionFlagName string
		if cmdPrefix == "" {
			failureActionFlagName = "FailureAction"
		} else {
			failureActionFlagName = fmt.Sprintf("%v.FailureAction", cmdPrefix)
		}

		failureActionFlagValue, err := cmd.Flags().GetString(failureActionFlagName)
		if err != nil {
			return err, false
		}
		m.FailureAction = failureActionFlagValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveServiceSpecRollbackConfigMaxFailureRatioFlags(depth int, m *models.ServiceSpecRollbackConfig, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	maxFailureRatioFlagName := fmt.Sprintf("%v.MaxFailureRatio", cmdPrefix)
	if cmd.Flags().Changed(maxFailureRatioFlagName) {

		var maxFailureRatioFlagName string
		if cmdPrefix == "" {
			maxFailureRatioFlagName = "MaxFailureRatio"
		} else {
			maxFailureRatioFlagName = fmt.Sprintf("%v.MaxFailureRatio", cmdPrefix)
		}

		maxFailureRatioFlagValue, err := cmd.Flags().GetFloat64(maxFailureRatioFlagName)
		if err != nil {
			return err, false
		}
		m.MaxFailureRatio = maxFailureRatioFlagValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveServiceSpecRollbackConfigMonitorFlags(depth int, m *models.ServiceSpecRollbackConfig, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	monitorFlagName := fmt.Sprintf("%v.Monitor", cmdPrefix)
	if cmd.Flags().Changed(monitorFlagName) {

		var monitorFlagName string
		if cmdPrefix == "" {
			monitorFlagName = "Monitor"
		} else {
			monitorFlagName = fmt.Sprintf("%v.Monitor", cmdPrefix)
		}

		monitorFlagValue, err := cmd.Flags().GetInt64(monitorFlagName)
		if err != nil {
			return err, false
		}
		m.Monitor = monitorFlagValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveServiceSpecRollbackConfigOrderFlags(depth int, m *models.ServiceSpecRollbackConfig, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	orderFlagName := fmt.Sprintf("%v.Order", cmdPrefix)
	if cmd.Flags().Changed(orderFlagName) {

		var orderFlagName string
		if cmdPrefix == "" {
			orderFlagName = "Order"
		} else {
			orderFlagName = fmt.Sprintf("%v.Order", cmdPrefix)
		}

		orderFlagValue, err := cmd.Flags().GetString(orderFlagName)
		if err != nil {
			return err, false
		}
		m.Order = orderFlagValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveServiceSpecRollbackConfigParallelismFlags(depth int, m *models.ServiceSpecRollbackConfig, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	parallelismFlagName := fmt.Sprintf("%v.Parallelism", cmdPrefix)
	if cmd.Flags().Changed(parallelismFlagName) {

		var parallelismFlagName string
		if cmdPrefix == "" {
			parallelismFlagName = "Parallelism"
		} else {
			parallelismFlagName = fmt.Sprintf("%v.Parallelism", cmdPrefix)
		}

		parallelismFlagValue, err := cmd.Flags().GetInt64(parallelismFlagName)
		if err != nil {
			return err, false
		}
		m.Parallelism = parallelismFlagValue

		retAdded = true
	}

	return nil, retAdded
}

// Extra schema cli for ServiceSpecUpdateConfig

// register flags to command
func registerModelServiceSpecUpdateConfigFlags(depth int, cmdPrefix string, cmd *cobra.Command) error {

	if err := registerServiceSpecUpdateConfigDelay(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerServiceSpecUpdateConfigFailureAction(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerServiceSpecUpdateConfigMaxFailureRatio(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerServiceSpecUpdateConfigMonitor(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerServiceSpecUpdateConfigOrder(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerServiceSpecUpdateConfigParallelism(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	return nil
}

func registerServiceSpecUpdateConfigDelay(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	delayDescription := `Amount of time between updates, in nanoseconds.`

	var delayFlagName string
	if cmdPrefix == "" {
		delayFlagName = "Delay"
	} else {
		delayFlagName = fmt.Sprintf("%v.Delay", cmdPrefix)
	}

	var delayFlagDefault int64

	_ = cmd.PersistentFlags().Int64(delayFlagName, delayFlagDefault, delayDescription)

	return nil
}

func registerServiceSpecUpdateConfigFailureAction(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	failureActionDescription := `Action to take if an updated task fails to run, or stops running during the update.`

	var failureActionFlagName string
	if cmdPrefix == "" {
		failureActionFlagName = "FailureAction"
	} else {
		failureActionFlagName = fmt.Sprintf("%v.FailureAction", cmdPrefix)
	}

	var failureActionFlagDefault string

	_ = cmd.PersistentFlags().String(failureActionFlagName, failureActionFlagDefault, failureActionDescription)

	return nil
}

func registerServiceSpecUpdateConfigMaxFailureRatio(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	maxFailureRatioDescription := `The fraction of tasks that may fail during an update before the failure action is invoked, specified as a floating point number between 0 and 1.`

	var maxFailureRatioFlagName string
	if cmdPrefix == "" {
		maxFailureRatioFlagName = "MaxFailureRatio"
	} else {
		maxFailureRatioFlagName = fmt.Sprintf("%v.MaxFailureRatio", cmdPrefix)
	}

	var maxFailureRatioFlagDefault float64

	_ = cmd.PersistentFlags().Float64(maxFailureRatioFlagName, maxFailureRatioFlagDefault, maxFailureRatioDescription)

	return nil
}

func registerServiceSpecUpdateConfigMonitor(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	monitorDescription := `Amount of time to monitor each updated task for failures, in nanoseconds.`

	var monitorFlagName string
	if cmdPrefix == "" {
		monitorFlagName = "Monitor"
	} else {
		monitorFlagName = fmt.Sprintf("%v.Monitor", cmdPrefix)
	}

	var monitorFlagDefault int64

	_ = cmd.PersistentFlags().Int64(monitorFlagName, monitorFlagDefault, monitorDescription)

	return nil
}

func registerServiceSpecUpdateConfigOrder(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	orderDescription := `The order of operations when rolling out an updated task. Either the old task is shut down before the new task is started, or the new task is started before the old task is shut down.`

	var orderFlagName string
	if cmdPrefix == "" {
		orderFlagName = "Order"
	} else {
		orderFlagName = fmt.Sprintf("%v.Order", cmdPrefix)
	}

	var orderFlagDefault string

	_ = cmd.PersistentFlags().String(orderFlagName, orderFlagDefault, orderDescription)

	return nil
}

func registerServiceSpecUpdateConfigParallelism(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	parallelismDescription := `Maximum number of tasks to be updated in one iteration (0 means unlimited parallelism).`

	var parallelismFlagName string
	if cmdPrefix == "" {
		parallelismFlagName = "Parallelism"
	} else {
		parallelismFlagName = fmt.Sprintf("%v.Parallelism", cmdPrefix)
	}

	var parallelismFlagDefault int64

	_ = cmd.PersistentFlags().Int64(parallelismFlagName, parallelismFlagDefault, parallelismDescription)

	return nil
}

// retrieve flags from commands, and set value in model. Return true if any flag is passed by user to fill model field.
func retrieveModelServiceSpecUpdateConfigFlags(depth int, m *models.ServiceSpecUpdateConfig, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false

	err, delayAdded := retrieveServiceSpecUpdateConfigDelayFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || delayAdded

	err, failureActionAdded := retrieveServiceSpecUpdateConfigFailureActionFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || failureActionAdded

	err, maxFailureRatioAdded := retrieveServiceSpecUpdateConfigMaxFailureRatioFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || maxFailureRatioAdded

	err, monitorAdded := retrieveServiceSpecUpdateConfigMonitorFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || monitorAdded

	err, orderAdded := retrieveServiceSpecUpdateConfigOrderFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || orderAdded

	err, parallelismAdded := retrieveServiceSpecUpdateConfigParallelismFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || parallelismAdded

	return nil, retAdded
}

func retrieveServiceSpecUpdateConfigDelayFlags(depth int, m *models.ServiceSpecUpdateConfig, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	delayFlagName := fmt.Sprintf("%v.Delay", cmdPrefix)
	if cmd.Flags().Changed(delayFlagName) {

		var delayFlagName string
		if cmdPrefix == "" {
			delayFlagName = "Delay"
		} else {
			delayFlagName = fmt.Sprintf("%v.Delay", cmdPrefix)
		}

		delayFlagValue, err := cmd.Flags().GetInt64(delayFlagName)
		if err != nil {
			return err, false
		}
		m.Delay = delayFlagValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveServiceSpecUpdateConfigFailureActionFlags(depth int, m *models.ServiceSpecUpdateConfig, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	failureActionFlagName := fmt.Sprintf("%v.FailureAction", cmdPrefix)
	if cmd.Flags().Changed(failureActionFlagName) {

		var failureActionFlagName string
		if cmdPrefix == "" {
			failureActionFlagName = "FailureAction"
		} else {
			failureActionFlagName = fmt.Sprintf("%v.FailureAction", cmdPrefix)
		}

		failureActionFlagValue, err := cmd.Flags().GetString(failureActionFlagName)
		if err != nil {
			return err, false
		}
		m.FailureAction = failureActionFlagValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveServiceSpecUpdateConfigMaxFailureRatioFlags(depth int, m *models.ServiceSpecUpdateConfig, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	maxFailureRatioFlagName := fmt.Sprintf("%v.MaxFailureRatio", cmdPrefix)
	if cmd.Flags().Changed(maxFailureRatioFlagName) {

		var maxFailureRatioFlagName string
		if cmdPrefix == "" {
			maxFailureRatioFlagName = "MaxFailureRatio"
		} else {
			maxFailureRatioFlagName = fmt.Sprintf("%v.MaxFailureRatio", cmdPrefix)
		}

		maxFailureRatioFlagValue, err := cmd.Flags().GetFloat64(maxFailureRatioFlagName)
		if err != nil {
			return err, false
		}
		m.MaxFailureRatio = maxFailureRatioFlagValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveServiceSpecUpdateConfigMonitorFlags(depth int, m *models.ServiceSpecUpdateConfig, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	monitorFlagName := fmt.Sprintf("%v.Monitor", cmdPrefix)
	if cmd.Flags().Changed(monitorFlagName) {

		var monitorFlagName string
		if cmdPrefix == "" {
			monitorFlagName = "Monitor"
		} else {
			monitorFlagName = fmt.Sprintf("%v.Monitor", cmdPrefix)
		}

		monitorFlagValue, err := cmd.Flags().GetInt64(monitorFlagName)
		if err != nil {
			return err, false
		}
		m.Monitor = monitorFlagValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveServiceSpecUpdateConfigOrderFlags(depth int, m *models.ServiceSpecUpdateConfig, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	orderFlagName := fmt.Sprintf("%v.Order", cmdPrefix)
	if cmd.Flags().Changed(orderFlagName) {

		var orderFlagName string
		if cmdPrefix == "" {
			orderFlagName = "Order"
		} else {
			orderFlagName = fmt.Sprintf("%v.Order", cmdPrefix)
		}

		orderFlagValue, err := cmd.Flags().GetString(orderFlagName)
		if err != nil {
			return err, false
		}
		m.Order = orderFlagValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveServiceSpecUpdateConfigParallelismFlags(depth int, m *models.ServiceSpecUpdateConfig, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	parallelismFlagName := fmt.Sprintf("%v.Parallelism", cmdPrefix)
	if cmd.Flags().Changed(parallelismFlagName) {

		var parallelismFlagName string
		if cmdPrefix == "" {
			parallelismFlagName = "Parallelism"
		} else {
			parallelismFlagName = fmt.Sprintf("%v.Parallelism", cmdPrefix)
		}

		parallelismFlagValue, err := cmd.Flags().GetInt64(parallelismFlagName)
		if err != nil {
			return err, false
		}
		m.Parallelism = parallelismFlagValue

		retAdded = true
	}

	return nil, retAdded
}
