name: Go

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - name: Set up Go
      uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
      with:
        go-version: stable
        check-latest: true
        cache: true
    
    - name: Install make
      run: sudo apt-get install make

    - name: Build
      run: make build

    - name: Save dockerctl executable
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: dockerctl-exe
        path: cmd/dockerctl/dockerctl
        retention-days: 1
  
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: download dockerctl executable
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: dockerctl-exe
          path: cmd/dockerctl
      
      - name: make artifact executable
        run: sudo chmod +x ./cmd/dockerctl/dockerctl

      - name: check docker engine
        run: docker version
      
      - name: Install make socat
        run: sudo apt-get install make socat

      - name: Expose Docker engine
        run: make expose-docker

      - name: run tests
        run: ./tests/main.sh
