name: Go

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.2
    
    - name: Install make
      run: sudo apt-get install make

    - name: Build
      run: make build

    - name: Save dockerctl executable
      uses: actions/upload-artifact@v2
      with:
        name: dockerctl-exe
        path: cmd/dockerctl/dockerctl
        retention-days: 1
  
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2

      - name: download dockerctl executable
        uses: actions/download-artifact@master
        with:
          name: dockerctl-exe
          path: cmd/dockerctl
      
      - name: make artifact executable
        run: sudo chmod +x ./cmd/dockerctl/dockerctl

      - name: check docker engine
        run: docker version
      
      - name: Install make socat
        run: sudo apt-get install make socat

      - name: Expose Docker engine
        run: make expose-docker

      - name: run tests
        run: ./tests/main.sh