name: Vulnerability scans

on:
  branch_protection_rule:
  push:
    branches: [ "master" ]
  schedule:
    - cron: '14 3 * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  scanners:
    permissions:
      contents: read
      security-events: write
    uses: go-openapi/ci-workflows/.github/workflows/scanner.yml@740d5649f5de40283e19bfd4c927ebe4c724523c # V0.4.4
    secrets: inherit
