name: Vulnerability scans

on:
  branch_protection_rule:
  push:
    branches: [ "master" ]
  schedule:
    - cron: '14 3 * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  scanners:
    permissions:
      contents: read
      security-events: write
    uses: go-openapi/ci-workflows/.github/workflows/scanner.yml@64ff9bddfc61cd8c5958e3bd421ec2730bd47c60 # V0.4.4
    secrets: inherit
