name: Vulnerability scans

on:
  branch_protection_rule:
  push:
    branches: [ "master" ]
  schedule:
    - cron: '14 3 * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  scanners:
    permissions:
      contents: read
      security-events: write
    uses: go-openapi/ci-workflows/.github/workflows/scanner.yml@ad78ceadc182b8ec34bbb6501327ce392e2ce504 # V0.4.4
    secrets: inherit
