// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// JoinTokens JoinTokens contains the tokens workers and managers need to join the swarm.
//
//
// swagger:model JoinTokens
type JoinTokens struct {

	// The token managers can use to join the swarm.
	//
	// Example: SWMTKN-1-3pu6hszjas19xyp7ghgosyx9k8atbfcr8p2is99znpy26u2lkl-7p73s1dx5in4tatdymyhg9hu2
	Manager string `json:"Manager,omitempty"`

	// The token workers can use to join the swarm.
	//
	// Example: SWMTKN-1-3pu6hszjas19xyp7ghgosyx9k8atbfcr8p2is99znpy26u2lkl-1awxwuwd3z9j1z3puu7rcgdbx
	Worker string `json:"Worker,omitempty"`
}

// Validate validates this join tokens
func (m *JoinTokens) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this join tokens based on context it is used
func (m *JoinTokens) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *JoinTokens) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *JoinTokens) UnmarshalBinary(b []byte) error {
	var res JoinTokens
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
